### ISSUE TITLE
Write Unit-Test For POST Opportunity API using Chai, Mocha and Sinon

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Backend#18] opened 2021-03-20 08:33 UTC
- The POST Opportunity API is divided into controllers, services, and managers, 
Tests should be written for each 3 of them. 
- Data should be mocked with Sinon. 
- This is the first test, so set up for chai, mocha also needs to be done. 
- Refer to [this](https://blog.logrocket.com/unit-testing-node-js-applications-using-mocha-chai-and-sinon/) for help

**Comment by Athira2199** [comment] 2021-03-20 10:50
Hi, I have never done unit-testing in NodeJS but would love to explore the opportunity if given a chance.  Since the issue is opened please allow me to take up the oppurtunity.

**Comment by Manvityagi** [comment] 2021-03-20 12:41
> Hi, I have never done unit-testing in NodeJS but would love to explore the opportunity if given a chance. Since the issue is opened please allow me to take up the oppurtunity.

Hi @Athira2199, there is an issue assigned to you already, only 1 issue can be assigned at one time. Please complete that first

**Comment by Sukriti-sood** [comment] 2021-03-21 14:06
@Manvityagi I would like to work on this, Please Assign this to me

**Comment by Manvityagi** [comment] 2021-03-21 14:54
> @Manvityagi I would like to work on this, Please Assign this to me

Assigned @Sukriti-sood, Go ahead. 
Feel free to ping on discord channel #opportunity-calendar-backend in case of any doubts.

**Comment by Sukriti-sood** [comment] 2021-03-27 06:34
@Manvityagi  I have written tests for manager and services facing problem in controllers like how to compare status code and json data.

**Comment by Manvityagi** [comment] 2021-03-28 12:05
> @Manvityagi I have written tests for manager and services facing problem in controllers like how to compare status code and json data.

Let's connect after Holi @Sukriti-sood

**Comment by Manvityagi** [comment] 2021-03-30 15:58
@Sukriti-sood , Can you make a PR for the services and managers test? The PR can be updated later with the controller's tests.

**Comment by Manvityagi** [comment] 2021-03-30 16:08
@Sukriti-sood 
In this article, Refer to the last part- `UserContoller class`, you will get a fair enough idea of how to write tests for our controllers. 
https://blog.logrocket.com/unit-testing-node-js-applications-using-mocha-chai-and-sinon/ 

If you still face any problems, feel free to ping.

**Comment by Manvityagi** [comment] 2021-04-03 05:54
@Sukriti-sood Any updates?

**Comment by Sukriti-sood** [comment] 2021-04-03 06:19
> @Sukriti-sood Any updates?

I have wriitten tests for manager and services and I am getting some errors while running tests related to require

Require  Reference not found ESM modeule,
Trying to resolve them , 

I will try to complete this issue today.

**Comment by Sukriti-sood** [comment] 2021-04-03 11:07
@Manvityagi Please help me I am continuously getting this Error
Earlier I was writing test in develop branch then I realised I haven't created Feature branch from that time I am getting this Error

![Screenshot from 2021-04-03 16-35-54](https://user-images.githubusercontent.com/55010599/113476740-f6b71480-949a-11eb-8f52-3ea754a16806.png)

**Comment by Manvityagi** [comment] 2021-04-03 14:27
> @Manvityagi Please help me I am continuously getting this Error
> Earlier I was writing test in develop branch then I realised I haven't created Feature branch from that time I am getting this Error
> 
> ![Screenshot from 2021-04-03 16-35-54](https://user-images.githubusercontent.com/55010599/113476740-f6b71480-949a-11eb-8f52-3ea754a16806.png)

Try using `import` in place of `require` 
```
import chai from 'chai'; 
import sinon from 'sinon'; 
import stubValue from './fakedata';

//same for all other `require`
```

**Comment by Manvityagi** [comment] 2021-04-03 14:28
> > @Manvityagi Please help me I am continuously getting this Error
> > Earlier I was writing test in develop branch then I realised I haven't created Feature branch from that time I am getting this Error
> > ![Screenshot from 2021-04-03 16-35-54](https://user-images.githubusercontent.com/55010599/113476740-f6b71480-949a-11eb-8f52-3ea754a16806.png)
> 
> @Sukriti-sood  Try using `import` in place of `require`
> 
> ```
> import chai from 'chai'; 
> import sinon from 'sinon'; 
> import stubValue from './fakedata';
> 
> //same for all other `require`
> ```

**Comment by Sukriti-sood** [comment] 2021-04-03 16:05
> > @Manvityagi Please help me I am continuously getting this Error
> > Earlier I was writing test in develop branch then I realised I haven't created Feature branch from that time I am getting this Error
> > ![Screenshot from 2021-04-03 16-35-54](https://user-images.githubusercontent.com/55010599/113476740-f6b71480-949a-11eb-8f52-3ea754a16806.png)
> 
> Try using `import` in place of `require`
> 
> ```
> import chai from 'chai'; 
> import sinon from 'sinon'; 
> import stubValue from './fakedata';
> 
> //same for all other `require`
> ```

I have tried this also for this I am getting module not defined

![Screenshot from 2021-04-03 21-40-52](https://user-images.githubusercontent.com/55010599/113484337-6a6e1700-94c5-11eb-8274-c5383f44eb22.png)

**Comment by Manvityagi** [comment] 2021-04-03 17:27
Can you pull the latest changes from repo and make a PR as it is.. So that I can debug on my system? @Sukriti-sood

**Comment by Manvityagi** [comment] 2021-04-05 09:38
Will update you soon on it @Sukriti-sood

**Closed as completed** 2021-04-15 04:14 UTC
Labels: GSSOC21, LEVEL3
